//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbCopy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbCopy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bulk Copy.
        /// </summary>
        public static string btnBulkCopy_Content {
            get {
                return ResourceManager.GetString("btnBulkCopy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string btnCancel_Content {
            get {
                return ResourceManager.GetString("btnCancel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co_nnect.
        /// </summary>
        public static string btnConnect_Content {
            get {
                return ResourceManager.GetString("btnConnect_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted connection.
        /// </summary>
        public static string chkDestEncrypt_Content {
            get {
                return ResourceManager.GetString("chkDestEncrypt_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted connection.
        /// </summary>
        public static string chkSourceEncrypt_Content {
            get {
                return ResourceManager.GetString("chkSourceEncrypt_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Query.
        /// </summary>
        public static string expander_Header {
            get {
                return ResourceManager.GetString("expander_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string grpDest_Header {
            get {
                return ResourceManager.GetString("grpDest_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string grpSource_Header {
            get {
                return ResourceManager.GetString("grpSource_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog:.
        /// </summary>
        public static string lblDestCatalog_Content {
            get {
                return ResourceManager.GetString("lblDestCatalog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string lblDestServer_Content {
            get {
                return ResourceManager.GetString("lblDestServer_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog:.
        /// </summary>
        public static string lblSourceCatalog_Content {
            get {
                return ResourceManager.GetString("lblSourceCatalog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string lblSourceServer_Content {
            get {
                return ResourceManager.GetString("lblSourceServer_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables to copy.
        /// </summary>
        public static string lstTables_ToolTip {
            get {
                return ResourceManager.GetString("lstTables_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string txtDestPass_ToolTip {
            get {
                return ResourceManager.GetString("txtDestPass_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string txtDestUser_ToolTip {
            get {
                return ResourceManager.GetString("txtDestUser_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string txtSourcePass_ToolTip {
            get {
                return ResourceManager.GetString("txtSourcePass_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string txtSourceUser_ToolTip {
            get {
                return ResourceManager.GetString("txtSourceUser_ToolTip", resourceCulture);
            }
        }
    }
}
